### ISSUE TITLE
Add section on available packaging & deployment options

### ISSUE THREAD

**Issue by ncoghlan** [developer-portal/content#1]
As discussed at Fedora E&S meeting on July 16, this would be aimed at helping to guide developers packaging different kinds of applications to appropriate packaging tools (Nulecule, xdg-app-, software collections)

**Comment by xsuchy** [comment]
I started working on this.

**Comment by asamalik** [comment]
Issues for this content have been created.

@xsuchy I have created an issue #45  for RPM content
