### ISSUE TITLE
Vagrant content should show how to run it with libvirt provider

### ISSUE THREAD

**Issue by asamalik** [developer-portal/content#102]
I would suggest to do the similar as in VirtualBox section:

"To use VirtualBox provider with any Vagrant commands, one has to explicitly append --provider=virtualbox."

**Comment by strzibny** [comment]
libvirt provider is the default (as mentioned), what am I missing?

**Comment by asamalik** [comment]
When a Vagrantfile defaults to VirtualBox and user installed libvirt and VirtualBox together on their machine.

We can say that libvirt is the default and it's not necessary to use this option, it might be useful in some cases.

**Comment by strzibny** [comment]
- If Vagrantfile supports only VirtualBox, user cannot use libvirt provider.
- If Vagrantfile supports libvirt, it will be used as a default.
- If Vagrantfile overrides provider, the switch won't work.

**Comment by asamalik** [comment]
OK, then it's probably fine to leave it as it is.
