### ISSUE TITLE
"Didn't work? Click here to open an issue."

### ISSUE THREAD

**Issue by asamalik** [developer-portal/content#103]
Do we want to encourage people to open an issue, if the guide didn't work for them?

We could provide a link on every page that would say something like: "Didn't work? Click here to open an issue."

**Comment by strzibny** [comment]
Do you want both a link to create an issue AND link to fix/edit the page?

**Comment by asamalik** [comment]
Probably not.

I just want to make sure, that it attracts both beginners and experienced developers.

It should give these two messages at the same time:
 - "Didn't it work for you and you don't know why? Let us know."
 - "Do you want to fix/extend/contribute to this page? Do it here."

**Comment by pvalena** [comment]
We could have some button which leads to creating a new issue next to "Edit this page" button, e.g. here:

https://developer.fedoraproject.org/start/sw/gui-app/about.html

**Comment by jackorp** [comment]
We currently have the "Edit this page" button, which leads to web editor on GitHub, and "Learn to contribute" on unfinished pages and on the bottom, both leading to the "How to contribute" [site](https://developer-portal.github.io/contributing/).

However, I find it useful adding something like `Report an issue` to content, as sometimes there are things users don't necessarily want to fix themselves or don't have the how-to, an example being #383 where an image was too large for the website. 
Or a hypothetical example: there is an outdated guide, someone tries it out, the set of steps don't work, they would like to report it, so they click on the `Report an issue` and report it.

**Comment by pvalena** [comment]
> However, I find it useful adding something like `Report an issue` to content, as sometimes there are things users don't necessarily want to fix themselves or don't have the how-to, an example being #383 where an image was too large for the website.
> Or a hypothetical example: there is an outdated guide, someone tries it out, the set of steps don't work, they would like to report it, so they click on the `Report an issue` and report it.

Yes, that input would be really useful. Let's do that.
