### ISSUE TITLE
Inconsistencies in Vagrant+Docker section

### ISSUE THREAD

**Issue by msrb** [developer-portal/content#110]
["Using Docker from Vagrant without password prompts"] section seems to be somehow inconsistent. First it tells me that "it is enough to add yourself to the vagrant group" and later it suggests to create docker group instead:
 "$ sudo groupadd docker && sudo gpasswd -a ${USER} docker && sudo systemctl restart docker"

["Using Docker from Vagrant without password prompts"]: https://github.com/developer-portal/content/blob/master/tools/vagrant/vagrant-docker.md#using-docker-from-vagrant-without-password-prompts

**Comment by strzibny** [comment]
Oh, it got copying from somewhere else and its wrong. Thank you for spotting it @msrb. Fixed in https://github.com/developer-portal/content/commit/80ad3aef09dc9a64912fa9163e05f47f7343157f.
