### ISSUE TITLE
virt-builder logo

### ISSUE THREAD

**Issue by phracek** [developer-portal/content#111]
We are missing virt-builder logo.
Could you please provide it?

@kashyapc Please take care it. Thankx.

**Comment by kashyapc** [comment]
@phracek Here we go.

Here is a PNG: https://kashyapc.fedorapeople.org/banner_virt-builder.png
And, the original SVG: http://libguestfs.org/virt-builder.svg

**Comment by strzibny** [comment]
@phracek Isn't this one related? https://github.com/developer-portal/website/pull/25

**Comment by phracek** [comment]
Yes. It is a duplicate.

**Comment by phracek** [comment]
I have opened issue coincidentally.
