### ISSUE TITLE
Including Arduino in the section "Languages and Databases"?

### ISSUE THREAD

**Issue by thozza** [developer-portal/content#117]
Unfortunately the Arduino content is not included anywhere on the developer portal, although it is ready. I know that you don't have enough content for embedded platform to have meaningful section. Therefore I think the Arduino content could be moved to the "languages and databases" section, until you have more content for embedded platforms.

And to support my idea - document proving that Arduino is technically also a language that is used to write programs for this embedded platform https://www.arduino.cc/en/Reference/Comparison

**Comment by asamalik** [comment]
I know and it's stupid of us to not show it anywhere. I will publish the start section with the content we have.

**Comment by asamalik** [comment]
https://developer.fedoraproject.org/start/hw/arduino/about.html
