### ISSUE TITLE
@development-tools package missing on the RPM Packaging on the Setup session

### ISSUE THREAD

**Issue by rafaelreuber** [developer-portal/content#120]
The [RPM Packaging on the Setup session](https://developer.fedoraproject.org/deployment/rpm/about.html) install two packages: fedora-packager rpmdevtools.
But according with the [How to create an RPM package](https://fedoraproject.org/wiki/How_to_create_an_RPM_package), you should to install the following three packages: @development-tools, fedora-packager and rpmdevtools

**Comment by phracek** [comment]
Well we have to clarify it.
I am not sure, if the group @development-tools is still needed.

**Comment by phracek** [comment]
@rafaelreuber Can you please send us PR for this issue?

**Comment by jackorp** [comment]
As [current Fedora documentation](https://docs.fedoraproject.org/en-US/quick-docs/creating-rpm-packages/) recommends only `fedora-packager` and `fedora-review` packages this update is no longer needed.
