### ISSUE TITLE
Eclipse

### ISSUE THREAD

**Issue by asamalik** [developer-portal/content#128]

**Comment by akurtakov** [comment]
Pull request #140 should fix it.

**Comment by akurtakov** [comment]
Pull request was merged. When is it supposed to make it to the web page?

**Comment by strzibny** [comment]
@akurtakov We do irregular updates of the site. It's all done in this repo: https://github.com/developer-portal/developer.fedoraproject.org

**Comment by jackorp** [comment]
Closing as #140 was merged.
