### ISSUE TITLE
Suggest to install @rubyonrails instead of independent packages

### ISSUE THREAD

**Issue by voxik** [developer-portal/content#139]
@strzibny wouldn't it be better to suggest to install the RoR comps group instead of set of packages?

**Comment by strzibny** [comment]
As I remember @rubyonrails was installing lot of other packages. I think I was updating the group but not sure for which version of Fedora. Most likely is fine for Fedora 24, 23.

**Comment by voxik** [comment]
I just would not need to open PR such as #138 ;) but feel free to close this issue

**Comment by strzibny** [comment]
@voxik it looks fine now, I think we can switch go groupinstall. Would you make a PR? :)

**Comment by pvalena** [comment]
This was resolved by
https://github.com/developer-portal/content/commit/900bc4e06c4cc15a73272a48a721d960f3d14862
Feel free to reopen if I am mistaken.
