### ISSUE TITLE
Invalid link in Scientific Python Stack subsection

### ISSUE THREAD

**Issue by pvalena** [developer-portal/content#165]
https://github.com/developer-portal/content/commit/b0ed78072094b4108078ac475762add649e8193c#diff-0037d2d83c239af0951d1f3ba2e83df0R11

The link target is 'v':

`[SciPy Stack](v)`

**Comment by pvalena** [comment]
@rpavelka @jhornice could you fix this, please?

**Comment by rpavelka** [comment]
Done: https://github.com/developer-portal/content/pull/166
