### ISSUE TITLE
Add Jupyter Notebook to Scientific Python Stack

### ISSUE THREAD

**Issue by hroncok** [developer-portal/content#193]
Here: https://developer.fedoraproject.org/tech/languages/python/scipy.html

Jupyter Notebook was added to Fedora 26. Let's mention it. (I can work on it later, this is mostly a note to myself.)

**Comment by brennv** [comment]
I'm stoked this got added to Fedora 26. Drafted up PR #209, comments welcome.

**Comment by pvalena** [comment]
Closed via #209.
