### ISSUE TITLE
DevAssistant project is dead

### ISSUE THREAD

**Issue by stratakis** [developer-portal/content#196]
The DevAssistant project is not maintained anymore upstream and is being retired from F26+ [0].

Would it make sense for the developer-portal to just remove all the references and content related to DevAssistant?

[0] https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/4EYPY4OB73FMBAVXKFHDZNR37ZWCU762/

**Comment by pvalena** [comment]
It is already removed. Please see https://github.com/developer-portal/content/commit/089f77282b7a8631b1fd32619de318ce08cf83d0

You can see the result [here](http://developer.fedorainfracloud.org/tools/devassistant/about.html).

You are welcome to open a PR in case you want to replace the remaining references with something meaningful.

Thanks!

**Comment by stratakis** [comment]
I see, should have checked the closed issues. Thanks!
