### ISSUE TITLE
laravel reference composer installation method

### ISSUE THREAD

**Issue by yotamN** [developer-portal/content#204]
Fedora have composer in the repo but the Laravel 5 page recommend to install composer by downloading a file from the internet with curl, is there a reason for it (maybe should explain why then)?

**Comment by pvalena** [comment]
Please look into commit history(there can be some message), or contact author for explanation. Alternatively you can create a PR with a different solution.
We do not create this content ourselves. We rely on [contributions](http://developer-portal.github.io/contributing/) to Fedora Developer Portal, as it is a community effort.

Please contact us on #developer-portal @Freenode or on [our ML](https://lists.fedoraproject.org/archives/list/developer-portal@lists.fedoraproject.org/) in case you have some questions.

I am closing this as it is not an issue relevant to the content(see [wiki](https://fedoraproject.org/wiki/Websites/Developer)).
