### ISSUE TITLE
OpenShift

### ISSUE THREAD

**Issue by asamalik** [developer-portal/content#21]

**Comment by strzibny** [comment]
OpenShift is not part of Fedora Project in any way. Let's think twice about doing content like this.

**Comment by bkabrda** [comment]
How so? It's packaged in Fedora and it's a Fedora-friendly way of deploying web applications. (Let's not deny the bonds that go through Red Hat here) IMO we should recommend a deployment option and OpenShift should be the one.

**Comment by strzibny** [comment]
Ok, we have the client packaged. Perhaps that makes sense after all.

**Comment by asamalik** [comment]
What we need here is an information about:
 - What is OpenShift Online (the current running OpenShift Online v2)
 - Basic info about web and cli interface
 - How to deploy an app (1. create, 2. git push, + link to other resources)

**Comment by mfojtik** [comment]
@mjelen PTAL

**Comment by sferich888** [comment]
@asamalik Do we really want to document OpenShift Online v2? The Enterprise Product just entered EOL (https://access.redhat.com/support/policy/updates/openshift) so I can only assume that its only a matter of time before OpenShift Online v2 is replaced by OpenShift Online v3. 

That said it might be simpler just to link to something like: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/User_Guide/index.html#chap-Getting_Started to provide you with the information your are looking for (for v2).

**Comment by phracek** [comment]
@sferich888 No, use only OpenShift Online v3.
