### ISSUE TITLE
Fix C# subsection formatting

### ISSUE THREAD

**Issue by pvalena** [developer-portal/content#214]
-   do not use multiple `<h1>` (`# Header` is a page title)
 -   use about.md as a landing page
 -   do not repeat `C#` in description(shown as a tile in lang section)
 -   do not repeat `C#` in other page titles (as in `C# - IDEs`)
 -   Use `$ sudo command` instead of `# command`

[Examples](http://developer.fedorainfracloud.org/tech/languages/csharp/dotnet-installation.html)

**Comment by pvalena** [comment]
@RheaAyase, PTAL.

**Comment by RheaAyase** [comment]
> do not repeat C# in description(shown as a tile in lang section)

I'm not sure what does that mean... this?

_description: "**C#** programming language, .NET Core and Mono open source frameworks."_

**Comment by RheaAyase** [comment]
> _description: "**C#** programming language, .NET Core and Mono open source frameworks."_

Reworded the above as well...

**Comment by pvalena** [comment]
> I'm not sure what does that mean... this?
Yes.

**Comment by pvalena** [comment]
Closed via #215.
