### ISSUE TITLE
Mono pages content needs fixes

### ISSUE THREAD

**Issue by pvalena** [developer-portal/content#217]
`.NET Framework API Reference`

does not seem to be fitting in [Mono page](https://developer.fedoraproject.org/tech/languages/csharp/mono-installation.html). 

The page is additionally missing 'subtitle' or 'introduction', after which would follow current content with 'Mono installation' (current page Title). The page title should be just 'Mono', to for this to  correspond with the title in left menu.

There is also no need to repeat 'Mono' in 'Mono Documentation'.

**Comment by pvalena** [comment]
@RheaAyase would you mind taking a look?

**Comment by pvalena** [comment]
Note that `C# IDEs in Fedora`(and maybe some other pages too) suffer from the same `Page title not corresponding to left menu` issue. Maybe we could fix this somehow globally?

**Comment by pvalena** [comment]
> I will actually highlight this issue on the mono list, see if they have an opinion. Mine would be that mono is an open source implementation of .net framework and the code reference applies with just minor exceptions...

Ok, thanks! In that case I'd at least mention it so noone else gets confused :)

**Comment by RheaAyase** [comment]
Yup, will see if we do communicate something with Mono SIG or.... or not :D

**Comment by tpokorra** [comment]
I am sorry for responding so late.

I have fixed the titles and subtitles.

About ".NET Framework API Reference": that does actually make sense IMHO. @RheaAyase has added that section, and it corresponds with the section "API Reference" on the page https://github.com/developer-portal/content/blob/master/tech/languages/csharp/dotnet-installation.md

**Comment by pvalena** [comment]
> I am sorry for responding so late.

No worries :)

> About ".NET Framework API Reference": that does actually make sense IMHO. @RheaAyase has added that section, and it corresponds with the section "API Reference" on the page https://github.com/developer-portal/content/blob/master/tech/languages/csharp/dotnet-installation.md

Well, in that case I'd mention (in `Documentation`) that the docs also apply to Mono \w minor differencies, as @RheaAyase [said](https://github.com/developer-portal/content/issues/217#issuecomment-316474447). That is IMHO not something one expects.

I'd also prefer linking the [docs](http://developer.fedorainfracloud.org/tech/languages/csharp/mono-installation.html#net-framework-api-reference), rather than duplicating content.

like so:
```
[link](/tech/languages/csharp/mono-installation.html#net-framework-api-reference)
```

**Comment by tpokorra** [comment]
I have tried to improve the section for the API documentation, saying that the Microsoft API documentation applies to Mono with minor differences.

I have no idea what you mean with "I'd also prefer linking the docs, rather than duplicating content." Are you refering to duplicate content between the Mono and Dotnet pages? But they are linking to completely different APIs?

**Comment by tpokorra** [comment]
Perhaps my words "it corresponds with the section "API Reference" on the page ..." lead you to think it was the same. I meant, that both pages have the same structure, but did not say that the content was the same.

**Comment by pvalena** [comment]
Thanks for straightening this up for me!

**Comment by jackorp** [comment]
Looks like the core issue was solved. Closing the issue.
