### ISSUE TITLE
Python: Make sure pipenv is covered

### ISSUE THREAD

**Issue by hroncok** [developer-portal/content#233]
> Pipenv is now *officially* the recommended tool on <a href="https://t.co/2Sz5dS2ZV5">https://t.co/2Sz5dS2ZV5</a> for managing application dependencies!!! ✨🍰✨ <a href="https://t.co/9XgLvsOpgZ">https://t.co/9XgLvsOpgZ</a></p>&mdash; Kenneth Reitz 🐍 (@kennethreitz) <a href="https://twitter.com/kennethreitz/status/936239842039619584?ref_src=twsrc%5Etfw">30. listopadu 2017</a>

We should make sure that pipev is covered in our Python sections. Currently, I don't see it packaged for Fedora at all.

cc @frenzymadness @encukou @mcyprian @fedora-python

**Comment by hroncok** [comment]
@pvalena Could you please assign me?

**Comment by encukou** [comment]
Please coordinate with Michal, he was looking into this.

**Comment by hroncok** [comment]
cc @mcyprian

**Comment by mcyprian** [comment]
Pipenv is not packaged for Fedora. If we consider Python 3 only package [pew](https://github.com/berdario/pew) should be the only missing dependency. I have a concept of spec file for pew, but the test suite is broken. I can help with packaging and the workflow for Python section as well. I was looking into Pipenv features a couple of weeks ago.

**Comment by hroncok** [comment]
pipenv is now packaged

**Comment by pvalena** [comment]
What's the status on this?

**Comment by hroncok** [comment]
Needs content. Not sure if @mcyprian would still want to cover this. If not, I'll do it, but October is crazy for me, I can only get to this next month.

**Comment by pvalena** [comment]
NP, thanks for status update.

**Comment by mcyprian** [comment]
I believe code snippets from magazine article https://fedoramagazine.org/install-pipenv-fedora/ can be reused here. I will try to find some time next week to make something up.

**Comment by girish946** [comment]
I would like to take up this issue.
I'm only confused about where should it be, under `tech/languages/python/pipenv.md` or `tools/pipenv/`?
Can someone help?

**Comment by hroncok** [comment]
I'd put it to `tech/languages/python/`.
