### ISSUE TITLE
move pages to proper subsections

### ISSUE THREAD

**Issue by yotamN** [developer-portal/content#237]
When there are a lot of pages on one subject it will be easier to find what you want with sub pages, for example in PHP there could be frameworks group with Symfony, Zend, CodeIgniter, Laravel etc.

Is it possible in the current template or does it require a change?

**Comment by pvalena** [comment]
For reference: http://developer-portal.github.io/doc/structure.html

`Start a project > Web Application > Laravel ... `
and 
`Tools > Web Server`
and
`Languages > PHP > Web Frameworks`

is what makes sense IMHO. Needs a bit of fixing though.

Thans for finding this!

**Comment by pvalena** [comment]
I think it should say
`Web Frameworks`
specifically.

http://developer.fedorainfracloud.org/tech/languages/php/php-frameworks.html

Also, no need to prefix the file with `php-` when it already is in php subsection.

**Comment by pvalena** [comment]
I've just learned that we can set permalinks to the duplicated pages. F.e.:
```
permalink: /tech/languages/php/laravel5.html

```

**Comment by yotamN** [comment]
@pvalena In web applications for example you could have HTTP servers, Static Site Generators and Web Frameworks as 3 subsections or probably sub subsections because  web applications is the sub section

**Comment by pvalena** [comment]
That seems to be overcomplication to me...
One could simply have a page `HTTP servers` that has a hyperlink list to other pages.

Like here: http://developer.fedorainfracloud.org/tech/languages/php/php-frameworks.html

**Comment by pvalena** [comment]
Feel free to submit a PR with any `cathegory` type of page you thing is missing.

**Comment by yotamN** [comment]
The example you gave of `Languages > PHP > Web Frameworks` could stay the same but instead of a page that contains link it will be an expandable list in the sidebar. The content will remain the same, just a bit more organized

**Comment by pvalena** [comment]
On top of that, you can actually prefix the page name in the pages list like so:
```
Frameworks
 - Zend
 - Laravel5
 - [ . . . ]
```

**Comment by yotamN** [comment]
Level of complexity to the site development or the content? It's true that the site will need some work to support it but after the initial work I don't think it will be that much complexity to the content writers

**Comment by jackorp** [comment]
Created new issue regarding this: #386
