### ISSUE TITLE
 Desktop C/C++ GUI application 

### ISSUE THREAD

**Issue by asamalik** [developer-portal/content#24]

**Comment by phracek** [comment]
@felipeborges: Could you please look at it? At least from C/C++ point of view.

**Comment by felipeborges** [comment]
@phracek Sure!

**Comment by strzibny** [comment]
In regards to this, we could probably cover Vala as a language (used within GNOME project).

**Comment by manjujidagi** [comment]
I am also interested in same topic ...
I need ur e-mail ID to contact you

**Comment by asamalik** [comment]
@manjujidagi that's great! You can use our mailing list: https://admin.fedoraproject.org/mailman/listinfo/developer-portal

**Comment by asamalik** [comment]
duplicate to #94
