### ISSUE TITLE
Create pages for Flatpak

### ISSUE THREAD

**Issue by pvalena** [developer-portal/content#245]
AFAIK there're no pages concerning flatpak, installation, usage etc.

**Comment by RheaAyase** [comment]
I've already poked our contributor who would like to look at this on Thursday, who said that he could look at it - @AxelSilverdew

**Comment by pvalena** [comment]
Great! Thanks!

**Comment by AxelSilverdew** [comment]
Hey, so I have the content for the flatpak page ready. Where do I put it? And what do I name the file?

**Comment by pvalena** [comment]
Great. I think it fits to [Deployment and distribute](https://developer.fedoraproject.org/deployment.html) section(`deployment` folder). File can be called anything you thing is fine (it's transparent for website view); f.e. `about.md` or `usage.md`.
Please do not forget to add [jekyll headers](http://developer-portal.github.io/doc/file-structure.html).

**Comment by pvalena** [comment]
Thus you should create a new [subsection](http://developer-portal.github.io/doc/structure.html), which also needs a icon [added](https://github.com/developer-portal/website/commit/94195317aed11652c81b0cc38df65f8f49d8509f) to website repository.

**Comment by pvalena** [comment]
@AxelSilverdew, thanks!

**Comment by AxelSilverdew** [comment]
@pvalena I submitted 2 PRs:

PR for [the flatpak logo](https://github.com/developer-portal/website/pull/58)
PR for [the flatpak subsection](https://github.com/developer-portal/content/pull/246)

**Comment by AxelSilverdew** [comment]
@pvalena 

I added an `about.md` for flatpak in `deployment/flatpak/`
I also submitted a [PR](https://github.com/developer-portal/website/pull/59) to add the Flatpak icon to the website repository.

**Comment by pvalena** [comment]
Thanks!
Will be closed via https://github.com/developer-portal/content/pull/247.
