### ISSUE TITLE
`docker compose` howto no longer works

### ISSUE THREAD

**Issue by RobTranquillo** [developer-portal/content#272]
Disclaimer: I'am very new to fedora and docker. So mea culpa if i'am forget something important.

The howto [about Docker](https://developer.fedoraproject.org/tools/docker/compose.html) seems to can't find the package `python-django`.

`$ sudo docker build --tag=fedora-django Fedora-Dockerfiles/Django`

> Sending build context to Docker daemon 22.02 kB
> Step 1/9 : FROM fedora
>  ---> cc510acfcd70
> Step 2/9 : MAINTAINER http://fedoraproject.org/wiki/Cloud
>  ---> Using cache
>  ---> 54697ce19c5c
> Step 3/9 : RUN dnf -y update && dnf clean all
>  ---> Using cache
>  ---> 06567264da2e
> Step 4/9 : RUN dnf -y install python-pip python-django git sqlite python-psycopg2 && dnf clean all
>  ---> Running in 975be71bcae6
> Fedora 28 - x86_64 - Updates                    819 kB/s |  20 MB     00:25
> Fedora 28 - x86_64                              1.2 MB/s |  60 MB     00:50
> Last metadata expiration check: 0:00:23 ago on Fri Jul 27 04:58:11 2018.
> **No match for argument: python-django**
> **Error: Unable to find a match**
> The command '/bin/sh -c dnf -y install python-pip python-django git sqlite python-psycopg2 && dnf clean all' returned a non-zero code: 1  

And i can't find the package manually using `$ sudo dnf search python-django\*`

> ======================================================================================================== Name Matched: python-django* ========================================================================================================
> python-django-tastypie-doc.noarch : Documentation for python-django-tastypie
> python-django-haystack-docs.noarch : Documentation for Django Haystack pluggable search
> python-django-bash-completion.noarch : bash completion files for Django
> python-django-classy-tags-doc.noarch : Documentation for django-classy-tags
> python-django-registration-doc.noarch : A user-registration application for Django - documentation

But the package [should be exist](http://rpms.famillecollet.com/rpmphp/zoom.php?rpm=python-django).

**Comment by pvalena** [comment]
This should actually be moved to `Websites` issues.
