### ISSUE TITLE
Bug AMD GPL at 1080 resolution

### ISSUE THREAD

**Issue by APakrohk** [developer-portal/content#276]
My laptops model is the Asus N551zu
The graphic model of this series is r9 m280x
[ASUS Web Page ](https://www.asus.com/Laptops/N551ZU/)
>But in Fedora

**neofetch**
![screenshot from 2018-08-15 09-01-58](https://user-images.githubusercontent.com/27810360/44131710-048e3eb2-a06a-11e8-96b7-6a01d1e3285e.png)

**sudo lshw -C display**
```
*-display                 
       description: VGA compatible controller
       product: Kaveri [Radeon R7 Graphics]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 1
       bus info: pci@0000:00:01.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:51 memory:b0000000-bfffffff memory:d0800000-d0ffffff ioport:f000(size=256) memory:feb00000-feb3ffff memory:c0000-dffff
  *-display
       description: Display controller
       product: Bonaire PRO [Radeon R9 M270X]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:53 memory:c0000000-cfffffff memory:d0000000-d07fffff ioport:e000(size=256) memory:fea00000-fea3ffff memory:fea40000-fea5ffff
```
**has problem with the system in games and video capture**

**Comment by pvalena** [comment]
In case you're referring to Fedora desktop issues I suggest you to file a bug on [Fedora's official bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora).

This Issue tracker is relevant only for [Fedora Developer Portal Website](https://developer.fedoraproject.org/).
