### ISSUE TITLE
Remove DevAssistant entirely

### ISSUE THREAD

**Issue by hroncok** [developer-portal/content#291]
So there is a page with DevAssisatnt at Developer Portal that says "DevAssistant is obsolete, use it for reference only"

I don't know what kind of reference is that supposed for, but maybe it's time to get rid fo that page entirely? Or at lest the big logo and link at https://developer.fedoraproject.org/tools.html

http://developer.fedoraproject.org/tools/devassistant/about.html

https://github.com/developer-portal/content/issues/194
https://github.com/developer-portal/content/issues/196

**Comment by pvalena** [comment]
You're right.

**Comment by pvalena** [comment]
Let's remove it from the tools page entry.

**Comment by gombosg** [comment]
This is still on the "tools" front page on the new portal.

**Comment by pvalena** [comment]
@gombosg well, looks like I didn't get around to it... PR's are welcome!

**Comment by gombosg** [comment]
OK, will do
