### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by phracek** [developer-portal/content#3]
We need to provide a docker content for developer so that they can play with docker on Fedora.
- How to install it
- how to create a docker file
- how to create a image
.....

**Comment by strzibny** [comment]
It would be nice to mention how to run docker without sudo with the security implications. Perhaps we can just link http://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/.
