### ISSUE TITLE
Release is pending

### ISSUE THREAD

**Issue by tmds** [developer-portal/content#317]
@pvalena it looks like https://github.com/developer-portal/content/pull/302 changes (merged 8 March) are not visible on https://developer.fedoraproject.org/tech/languages/dotnet/about.html?

The left hand menu should say '.NET Core' as the second item and link to a page named 'dotnetcore.html' (content from https://github.com/developer-portal/content/blob/master/tech/languages/dotnet/dotnetcore.md).

**Comment by pvalena** [comment]
You're right. The website is on manual release schedule and I did not get around to make a release... And noone else is around to do+review it :) .. If I do a [staging] build, will you be able to take a look on / review the changes?

**Comment by RheaAyase** [comment]
@pvalena Hi, we can review our changes / pages, but I can't talk about the other PR's that were merged and will need reviewing... We could collect all the people who submitted these and ask them for review of the staging though! If you need some help with it please feel free to ping me =)

**Comment by pvalena** [comment]
@RheaAyase, sure, I'll build it then for staging ASAP.

It's not about the content correctness though, as that has been reviewed already in the PR. It's just a "sanity" and "styling" check - whether the page is and "looks" ok; and changes are propagated correctly (the content is there).

That means there are two things to check:  **git diff** (master branch) and the resulting **generated page** (on staging).

I'll post here when it's done.

**Comment by pvalena** [comment]
@tmds, @RheaAyase, et al.,
I've just prepared release on staging:

 -  https://developer.stg.fedoraproject.org/
 -  https://github.com/developer-portal/developer.fedoraproject.org/commit/81bfedbf0174273a402391a4e555b1b557688f7a

Please review, and **+1** here if you did find everything ok.
_ _ _ _

Specific links to files changed (some might've been deleted):
  https://developer.stg.fedoraproject.org/start/sw/web-app/laravel5.html
  https://developer.stg.fedoraproject.org/tech/database/mongodb/about.html
  https://developer.stg.fedoraproject.org/tech/database/sqlite/about.html
  https://developer.stg.fedoraproject.org/tech/languages/c/gtk.html
  https://developer.stg.fedoraproject.org/tech/languages/csharp/dotnet-installation.html
  https://developer.stg.fedoraproject.org/tech/languages/dotnet/about.html
  https://developer.stg.fedoraproject.org/tech/languages/dotnet/dotnet-ide.html
  https://developer.stg.fedoraproject.org/tech/languages/dotnet/dotnet-sig.html
  https://developer.stg.fedoraproject.org/tech/languages/dotnet/dotnet.html
  https://developer.stg.fedoraproject.org/tech/languages/dotnet/dotnetcore.html
  https://developer.stg.fedoraproject.org/tech/languages/dotnet/mono-sig.html
  https://developer.stg.fedoraproject.org/tech/languages/dotnet/mono.html
  https://developer.stg.fedoraproject.org/tech/languages/gjs/gjs-installation.html
  https://developer.stg.fedoraproject.org/tech/languages/go/go-programs.html
  https://developer.stg.fedoraproject.org/tech/languages/haskell/haskell-installation.html
  https://developer.stg.fedoraproject.org/tech/languages/python/multiple-pythons.html
  https://developer.stg.fedoraproject.org/tech/languages/ruby/ruby-installation.html

**Comment by tmds** [comment]
lgtm, thanks!

**Comment by pvalena** [comment]
Lets merge it then.

**Comment by pvalena** [comment]
I'll open a new issue for next release and link it here.
In the meantime, grab a pull request and review it!
