### ISSUE TITLE
Having more content regarding working on existing Fedora packages

### ISSUE THREAD

**Issue by da-x** [developer-portal/content#324]
For developers outside the Fedora community doing systems integration, the process of patching existing packages for bugs/features seems quite foreign.

Recently I wrote [a blog post](https://blog.aloni.org/posts/how-to-easily-patch-fedora-packages/) about it.

It may be helpful to add similar content about it in official Fedora sites.

**Comment by pvalena** [comment]
This is aimed at `https://developer.fedoraproject.org/` solely. If you find your content fits somewhere feel free to open a PR. Let me know If you get stuck somewhere, but please check our [contributing guide](http://developer-portal.github.io/contributing/) first.

_ _ _ _

Closing, as `having more content` is what we need in general :).
