### ISSUE TITLE
RFE: Add a quick start guide for R language

### ISSUE THREAD

**Issue by hhorak** [developer-portal/content#330]
R language is one of the stacks we have in Fedora (and epel), so it might make sense to have a page for this language. Although Python seems to be taken some part of the R market, according to articles like https://www.datanami.com/2019/08/15/is-python-strangling-r-to-death/. Still, R is quite popular in data science.

**Comment by Enchufa2** [comment]
I can contribute to this. I contribute as a packager (FAS: iucar) mainly for the R stack, and I maintain an info page (see [Pagure repo](https://pagure.io/R/fedora-r-packages)) that is published on the [R project website](https://cran.r-project.org/bin/linux/fedora/). We could take that content and adapt it for the Developer Portal.

**Comment by pvalena** [comment]
@Enchufa2 thanks!
Check our contribution guide: https://developer-portal.github.io/contributing/

Also, there's a easy way now to test the content, with updated Docker: https://github.com/developer-portal/website/blob/master/DEVELOPMENT.md
