### ISSUE TITLE
Improve contribution guidelines to the repo

### ISSUE THREAD

**Issue by vpavlin** [developer-portal/content#34]
As we talked on Environment & Stacks WG meeting

http://meetbot.fedoraproject.org/fedora-meeting-2/2015-07-30/env-and-stacks.2015-07-30-12.00.html/

There should probably be some "rules" enforced during content addition.
1. Every section should have editor - i.e. subject matter expert has to review all content changes for the given section
2. Before starting work on a specific topic, issue has to be created and draft should be linked from this issue so that editors and others can review and comment the draft early
3. Every content change needs to be proposed as a Pull Request and needs to get LGTM from two editors (if the PR submitter is also an editor, only one LGTM from another editor is ok to merge)

I guess, at least in the beginning, it will be hard to get editors for all the content, but it should definitely be one of the goals.

**Comment by asamalik** [comment]
+1

**Comment by strzibny** [comment]
I mostly agree.

**Comment by strzibny** [comment]
We started to work on the guidelines: https://github.com/developer-portal/content/blob/master/CONTRIBUTING.md.

**Comment by jackorp** [comment]
Current Contribution guidelines reside here: https://developer-portal.github.io/.

Feel free to reopen this issue if further work is needed.
