### ISSUE TITLE
dotnet and csharp confusion with outdated pages compared to this repository

### ISSUE THREAD

**Issue by tpokorra** [developer-portal/content#354]
From the start page, https://developer.fedoraproject.org/tech.html, there is still a link to 
https://developer.fedoraproject.org/tech/languages/csharp/dotnet-installation.html, which I cannot find in this repository.
That page shows outdated content, with broken links, and not telling about dotnet-core in Fedora 32.

I would expect to see https://github.com/developer-portal/content/blob/master/tech/languages/dotnet/about.md

Does the page just need a rebuild?

**Comment by pvalena** [comment]
Yes, you're right. Rebuild is needed. See https://github.com/developer-portal/website/pull/104#issuecomment-662195033.

**Comment by pvalena** [comment]
Rebuilt.
