### ISSUE TITLE
groovy instructions 

### ISSUE THREAD

**Issue by pwright** [developer-portal/content#364]
https://github.com/developer-portal/content/blob/master/tech/languages/groovy/groovy-installation.md didn't work for me, not sure if fedora packages groovy at all?

**Comment by pvalena** [comment]
Hello, thanks for the issue.

I can confirm groovy was removed from Fedora:
https://src.fedoraproject.org/rpms/groovy

**Comment by jackorp** [comment]
Closed in favor of tracking issue developer-portal/content#421.
