### ISSUE TITLE
Cassandra Page Out Of Date Removal

### ISSUE THREAD

**Issue by JKomoroski** [developer-portal/content#388]
As far as I can tell, the `cassandra` and `cassandra-server` packages are no longer in fedora. This page seems out of date and misleading. 

[content/tech/database/cassandra/about.md]()

Am I missing a prerequisite step to installing the dnf package? Dnf output:

```

% dnf se cassandra
Last metadata expiration check: 0:17:51 ago on Wed 14 Jul 2021 01:24:08 PM MDT.
======================================================================================================= Summary Matched: cassandra =======================================================================================================
golang-github-gocql-devel.noarch : Fast and robust cassandra client for the Go
```

**Comment by jackorp** [comment]
Hmm, the package seems retired for a few releases already, the current lines about installation should be replaced with some other approach as well as the `Language connectors/adapters/drivers (packages)` section. Other parts seem look good to me.

**Comment by jackorp** [comment]
This was addressed by adding a deprecation notice, and the page will be removed in the future (current plan: date of deprecation + 6 months) to allow for a contribution to bring the guide to some usable state.
