### ISSUE TITLE
: dotnet dotnet-ide.md

### ISSUE THREAD

**Issue by leonardon397** [developer-portal/content#407]
When trying to install eclipse, I followed all the steps presented and even so I got the following message printed on my terminal below (it's in Portuguese):
```shell
[leonardo@fedora ~]$ sudo dnf install eclipse eclipse-mpc
Fedora 35 - x86_64                                   110 kB/s |  43 kB     00:00    
Última verificação de data de vencimento de metadados: 0:00:01 atrás em qui 23 dez 2021 19:32:31.
Sem correspondência para o argumento: eclipse
Sem correspondência para o argumento: eclipse-mpc
Erro: Impossível de encontrar uma correspondência: eclipse eclipse-mpc
```

Translating to english, it means
```shell
[leonardo@fedora ~]$ sudo dnf install eclipse eclipse-mpc
Fedora 35 - x86_64                                   110 kB/s | 43 kB     00:00
Last metadata expiration date check: 0:00:01 ago on Thu Dec 23, 2021 19:32:31.
No match for argument: eclipse
No match for argument: eclipse-mpc
Error: Unable to find a match: eclipse eclipse-mpc
```

Please what should I do to resolve this issue?

**Comment by leonardon397** [comment]
Important info: I forgot to mention that, I am a Fedora 35 user, at the time I opened this issue.

**Comment by jackorp** [comment]
Thanks for the report!

Hmm... it seems eclipse has been orphaned for some time[1], this will require a content update.

Alternatively, I was able to install eclipse and access the marketplace through the flatpak version.

```console
$ flatpak install org.eclipse.Java
```

[1] https://src.fedoraproject.org/rpms/eclipse/blob/rawhide/f/dead.package

**Comment by leonardon397** [comment]
> Thanks for the report!
> 
> Hmm... it seems eclipse has been orphaned for some time[1], this will require a content update.
> 
> Alternatively, I was able to install eclipse and access the marketplace through the flatpak version.
> 
> ```
> $ flatpak install org.eclipse.Java
> ```
> 
> [1] https://src.fedoraproject.org/rpms/eclipse/blob/rawhide/f/dead.package

OK, I'm going to install from flatpak, until the problem is resolved!
