### ISSUE TITLE
Request for making a directory "Dart" in the tech/language

### ISSUE THREAD

**Issue by tahmid56** [developer-portal/content#412]
Flutter is framework for building cross platform application. The only language used in flutter framework to build cross platform app is Dart. So please add a directory in the tech/language named Dart. I have a little bit idea about how to get started with flutter. I can contribute. Thanks

**Comment by jackorp** [comment]
Hi, thanks for contributing.

Git does not store directories with no content. Instead, first create a directory locally, then create a file (with content), and then commit the file.
Like so:
```console
$ mkdir tech/languages/dart
$ vim tech/languages/dart/about.md # create a file with content
$ git add tech/languages/dart/about.md # this will add the file with the directory
$ git commit
# commit and push changes to your fork ...
```
