### ISSUE TITLE
tools: eclipse about.md

### ISSUE THREAD

**Issue by erkkiruohtula** [developer-portal/content#413]
The "eclipse" package does not seem to be available any more, so this page is  obsolete.
fedora:.../~$ sudo dnf install eclipse
[sudo] password for ruohtula: 
Last metadata expiration check: 0:01:47 ago on Thu 30 Dec 2021 10:21:41 EET.
No match for argument: eclipse
Error: Unable to find a match: eclipse

**Comment by jackorp** [comment]
We are aware of this problem, a fix is TBD.
A workaround is installing the Eclipse IDE from flatpak as outlined here: https://github.com/developer-portal/content/issues/407#issuecomment-1000775511

I will close this issue once a fix is committed to the repository.
