### ISSUE TITLE
start-hw: arduino about.md

### ISSUE THREAD

**Issue by GEPLinux** [developer-portal/content#417]
Describe the problem
**Not allowed to connect to the Arduino boards**
Except if :+1: 
**su -c ' usermod -a -G dialout,lock,uucp <UserName> ; reboot; ' ;**

**Comment by GEPLinux** [comment]
su -c ' dnf -y install snapd; ln -s /var/lib/snapd/snap /snap; snap install arduino; usermod -a -G dialout,lock,uucp ; reboot; ' ;

**Comment by pvalena** [comment]
https://src.fedoraproject.org/rpms/arduino
