### ISSUE TITLE
tech-database: mongodb about.md

### ISSUE THREAD

**Issue by CorruptComputer** [developer-portal/content#426]
The instructions on this page are wrong: https://developer.fedoraproject.org/tech/database/mongodb/about.html

On default Fedora 35 installation the following errors are shown when trying to install this with the shown commands:
```
[username@hostname ~]$ sudo dnf install mongodb mongodb-server
Last metadata expiration check: 2:57:12 ago on Fri 22 Apr 2022 04:26:06 PM EDT.
No match for argument: mongodb
No match for argument: mongodb-server
Error: Unable to find a match: mongodb mongodb-server
```

**Comment by jackorp** [comment]
Unfortunately, this is a known issue: https://github.com/developer-portal/content/issues/346

I am not sure if we should remove the page completely considering that MongoDB was removed due to the new licensing or point it to upstream documentation on this.

**Comment by jackorp** [comment]
Will be fixed by https://github.com/developer-portal/content/pull/456

**Comment by Melophip** [comment]
Can I be assigned this issue?

**Comment by jackorp** [comment]
Should be fixed by now and for now.
