### ISSUE TITLE
tools: eclipse about.md

### ISSUE THREAD

**Issue by Louis9902** [developer-portal/content#428]
I think eclipse is not in the repos anymore, since I'm not able to install it anymore. I'm current on fedora 35.

**Comment by jackorp** [comment]
Hi, thanks for the report, the eclipse packages were retired in Fedora 35 and the pages did not receive the required love they need. I am working on replacing the references with references to the eclipse flatpak package.

**Comment by Louis9902** [comment]
Thank you and sorry for the duplicate, I didn't check before reporting it.
