### ISSUE TITLE
start-hw: arduino about.md

### ISSUE THREAD

**Issue by git-user44** [developer-portal/content#436]
Forced to upgrade because of end of life of Fedora Core 34, I have now discover that the Arduino IDE no longer exists in FC35.

Following the instructions here [https://developer.fedoraproject.org/start/hw/arduino/about.html](url) results in...

flatpak install cc.arduino.arduinoide
Looking for matches…
error: No remote refs found similar to ‘cc.arduino.arduinoide’

So what does that mean ? No more arduino development on Fedora ?

**Comment by jackorp** [comment]
Hi, thanks for reaching out.

Hmm, I may have forgotten a step, you also need to add the flathub remote. See this page for more info: https://developer.fedoraproject.org/deployment/flatpak/flatpak-usage.html

As to the last question, yes, arduino is no longer packaged in Fedora as it was orphaned for lack of time, see reason on this page: https://src.fedoraproject.org/rpms/arduino
