### ISSUE TITLE
: c gtk.md

### ISSUE THREAD

**Issue by irww** [developer-portal/content#463]
On this page

https://developer.fedoraproject.org/tech/languages/c/gtk.html

it says

sudo dnf install devhelp gtk3-devel-docs gstreamer1-devel-docs clutter-doc

When run, 

No match for argument: gstreamer1-devel-docs
Error: Unable to find a match: gstreamer1-devel-docs

**Comment by jackorp** [comment]
Thanks for the report! gstreamer1-devel-docs had not been built for some time due to missing dependencies.

I'll remove it for now.
