### ISSUE TITLE
tech-languages: rust rust-installation.md

### ISSUE THREAD

**Issue by DStraniti** [developer-portal/content#465]
On the "Further Reading" section, installing 'rustup' is recommended before configuring an IDE or editor. However, when installing 'rustup' it promts to uninstall rust first. This is confusing and it is unknown the state of my system if I choose to ingore this warning.

It seems that either the 'rustup' recommendation should tell us to "ignore this check and install anyhow - this method is compatible with the dnf method...", or the the rust programming installation page should mention that there are 2 paths to installing Rust: dnf & rustup? And then explain the differences.

**Comment by matusf** [comment]
I have a slightly related issue, so I'll not open a new one. There could be a guide on how to use different versions of Rust. e.g. how to install rust-nightly. afaik now it is only possible via rustup.

**Comment by jackorp** [comment]
Hmm, so rustup seems to be recommended mainly for the IDE plugin judging by the https://github.com/rust-lang/vscode-rust#quick-start I unfortunately do not use rust with IDEs or as my daily language so I cannot verify the place of rustup in the ecosystem.

From what I understand, rust-analyzer does not need rustup in any way I am aware of and the system installation should suffice.

So I do not think that rustup should be in there today. A separate section in Rust installation could be better.

**Comment by Melophip** [comment]
Can I be assigned this issue
