### ISSUE TITLE
rpmbuild may not download the source code if disable_source_fetch is defined.

### ISSUE THREAD

**Issue by bschonec** [developer-portal/content#477]
In the deployment/rpm/about.md file the documentation states to run:

rpmbuild -ba hello.spec

If deisable_source_fetch is enabled/true, rpmbuild may not automatically download the source from ftp.gnu.org unless the

--undefine=_disable_source_fetch

parameter is set.  I recommend updating the documentation so that the source tarball is downloaded.

rpmbuild -ba --undefine=_disable_source_fetch

**Comment by jackorp** [comment]
the setup section on the same page explicitly states `wget http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz`, which is the way the sources are retrieved here.
