### ISSUE TITLE
haskell.org/ghcup/ is recommended way to install since 2022 ("The Haskell Platform" is deprecated)

### ISSUE THREAD

**Issue by lineality** [developer-portal/content#493]
regarding text on: https://developer.fedoraproject.org/tech/languages/haskell/haskell-installation.html

"The Haskell Platform" that is described describes itself this way at https://www.haskell.org/platform/:

"Haskell Platform
The Haskell Platform is deprecated
The Haskell Platform is deprecated since 2022 and is no longer the recommended way of installing Haskell. For the latest recommended way to install Haskell please see the [Downloads](https://www.haskell.org/downloads/) page."

https://www.haskell.org/ghcup/ appears to be the recommended way to install.

**Comment by jackorp** [comment]
Thanks for noticing that. Not sure if it makes sense to leave that link there. Looking into the [waybackmachine](https://web.archive.org/web/20211002061803/https://www.haskell.org/platform/) for that site The page seems to have been basically the line `sudo dnf install haskell-platform`.

The package still exists in Fedora and seems up-to-date and serves the purpose of pulling in dependencies to prepare environment for developer. I think removing the link makes more sense with intent of adding new section for upstream installs kind of like with special section for Ruby's rbenv https://developer.fedoraproject.org/tech/languages/ruby/ruby-installation.html#installing-ruby-with-rbenv
