### ISSUE TITLE
: vagrant vagrant-nfs.md sudoers configuration does not work (anymore)

### ISSUE THREAD

**Issue by martinclauss** [developer-portal/content#495]
Hey there! :wave:

The `/etc/sudoers` configuration from [here](https://developer.fedoraproject.org/tools/vagrant/vagrant-nfs.html) does not work (anymore). The instructions from here work fine: https://developer.hashicorp.com/vagrant/docs/synced-folders/nfs#root-privilege-requirement

```
Cmnd_Alias VAGRANT_EXPORTS_CHOWN = /bin/chown 0\:0 /tmp/vagrant-exports
Cmnd_Alias VAGRANT_EXPORTS_MV = /bin/mv -f /tmp/vagrant-exports /etc/exports
Cmnd_Alias VAGRANT_NFSD_CHECK = /usr/bin/systemctl status --no-pager nfs-server.service
Cmnd_Alias VAGRANT_NFSD_START = /usr/bin/systemctl start nfs-server.service
Cmnd_Alias VAGRANT_NFSD_APPLY = /usr/sbin/exportfs -ar
%vagrant ALL=(root) NOPASSWD: VAGRANT_EXPORTS_CHOWN, VAGRANT_EXPORTS_MV, VAGRANT_NFSD_CHECK, VAGRANT_NFSD_START, VAGRANT_NFSD_APPLY
```

Tested on Fedora 39.

Thanks! :heart:

**Comment by jackorp** [comment]
Thanks for the report and verifying a working way. Looks like vagrant is using a new way to manage the exports.
