### ISSUE TITLE
Content for Fedora 23 Feature Set

### ISSUE THREAD

**Issue by phracek** [developer-portal/content#5]
Fedora 23 Feature set should be a part of content.

Later on Features since F22 should be created too.

**Comment by phracek** [comment]
Fedora 23 Feature set is done by commit https://github.com/developer-portal/content/commit/0cf1a6e37957bd77ce2ec052cde6fb9eb62ea92a

**Comment by asamalik** [comment]
Do we want to include this? It might not be relevant for the target audience.

**Comment by strzibny** [comment]
We should not include it this way. We might select the interesting stuff, but not blindly copy official list from the wiki.

**Comment by asamalik** [comment]
This issue is outdated. If it's still relevant, let's discuss it on the mailing list.
