### ISSUE TITLE
Since `rbenv` is suggested for installing Ruby it could be nice at least mention `nodenv`

### ISSUE THREAD

**Issue by jackorp** [developer-portal/content#502]
A thought I had, since `rbenv` is suggested for installing Ruby it could be nice at least mention `nodenv`? I think for Fedora the best option is [installing using git](https://github.com/nodenv/nodenv?tab=readme-ov-file#basic-github-checkout)

_Originally posted by @dirschn in https://github.com/developer-portal/content/pull/498#discussion_r1434588117_

**Comment by dirschn** [comment]
I can make a pull request for this either today or tomorrow.
