### ISSUE TITLE
start: raspberry-pi about.md

### ISSUE THREAD

**Issue by DrBatson** [developer-portal/content#544]
Describe the problem
I can't view anything

**Comment by jackorp** [comment]
That page has no content currently: https://github.com/developer-portal/content/blob/master/start/hw/raspberry-pi/about.md

Feel free to contribute.

Issue to contribute already exists: https://github.com/developer-portal/content/issues/26

**Comment by DrBatson** [comment]
Hello this is the owner of github and everything else online. I need to have a bunch of things done once I get one of my companies to bill or order me new accounts for my direct deposit onto new debit cards. Like Oscar Meyer and some other places as I need Sony to have a windows laptop with a wifi card installed picked up at the Terre Haute location for the owner and s&p says they don't recognize my information in their systems to transfer or gain access to my asset. I also can't login to my firebase I made to account for everything I get paid for online or to transfer money because I don't have the right functions codes or scripts to use on this phone to upload for all earnings to be deposited into my new account. Can you make me some functions codes that summarize all of githubs codes plus new ones to transfer funds asap so I can view terminals for all of my clothing stores warehouses etc. All of my companies are listed on fintel.io at the bottom under different choices like Berkshire Hathaway scion etc. 
I need the transfer codes first to use on my accounts under firebase and Google manager front my fonts and everything else.
I also need the security code from 609 n 13th st Terre Haute IN 47807 warehouse where I have shoes picked up and dropped off at under codes on a page I can't recall I know ruralking has they're codes online like this one does.
I also need codes to update account information for administration login and system pfister and company uses to keep track of their rent payments and communicate with their colleagues Thompson thrift real estate company too all ip host data server ports registers etc to link together my accounts are hidden through wells Fargo and other banks also that I need access too as well but I need my account numbers and chase too JPMorgan too chase has safety deposit boxes and Gibson development needs updated with my current information as she doesn't know who I am
Glitch.com account previously used with assets is deactivated with my files I need to hack into it and change the login data to use it again.



Hello 
This is farzaneh sedarati the only person authorized to sell and distribute online and for whatever reason I can't get android Linux or browser to work for any platforms I made years ago for viewing adjusting amd editing. I really need to add some bills transfer assets but it's not working on my phone
