### ISSUE TITLE
Contribution links for the Developer Portal itself

### ISSUE THREAD

**Issue by ncoghlan** [developer-portal/content#60]
I couldn't find a link from the Portal back to this repo. Perhaps there could be an "About" page or similar that describes how to report problems and contribute fixes?

**Comment by strzibny** [comment]
Yes, it's a good idea. We can link it from the footer I guess.

**Comment by strzibny** [comment]
This is done in https://github.com/developer-portal/website/commit/7300a58714687ef2209d2b32a293c182781af0ad. Closing.
