### ISSUE TITLE
Make the headlines the same

### ISSUE THREAD

**Issue by strzibny** [developer-portal/content#69]
Some headlines are camel-cased, some not. We should use just one style.

e.g. My Headline About Something
vs  My headline about something

I prefer the latter.

**Comment by asamalik** [comment]
In English, **The First Variant** is correct (as opposed to Czech)

http://english.stackexchange.com/questions/14/which-words-in-a-title-should-be-capitalized

**Comment by strzibny** [comment]
> In English, The First Variant is correct (as opposed to Czech)

That's simply not true. You can always capitalize as normal sentence which many English sites do *including* redhat.com, getfedora.org, Fedora wiki, etc....and as I said I would really prefer it.

**Comment by strzibny** [comment]
This is now done for the already submitted content here: https://github.com/developer-portal/content/commit/f1c5adc2a51f4bc4cda2b11a84cf1c2ce1805daf

I updated the guidelines as well.
