### ISSUE TITLE
Perl

### ISSUE THREAD

**Issue by asamalik** [developer-portal/content#8]

**Comment by phracek** [comment]
This is partially fixed by commit https://github.com/developer-portal/content/commit/d40900e6b0ead2919049576df7c1a642f8db8177

Dancer is missing and is going to be added soon.

**Comment by strzibny** [comment]
I edited the text to match other content including the conversion to markdown.

I am missing Dancer/Dancer2 as mentioned by @phracek + perhaps Catalyst? Or is it not really packaged? I see some components but don't know the way how to install the framework itself.
