### ISSUE TITLE
Images in content

### ISSUE THREAD

**Issue by FrostyX** [developer-portal/content#99]
It would be nice to have possibility to show images in the content. It doesn't make much sense for programming languages and CLI stuff, but in some cases it might be fine:

1. Showing image with end result as a motivation (I am working on Sphinx tutorial, and I think screenshot of some documentation would be nice)
2. Showing some GUI/Web tool (From current content it can be DevAssistant and Copr)
3. ...

**Comment by pvalena** [comment]
It is possible to attach images, f.e.:

https://github.com/developer-portal/content/commit/6dbd8448556eff0626c1ba39590cb76e141c73e9

Thank you!
